name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build Modpack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./.github/actions
      env:
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
